apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
spec:
  storageClassName: nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/shared
    server: 3.120.244.249
    readOnly: false
